feat(binary-sensor): adding in binary sensor support for doors and windows
t0bst4r/matterbridge-home-assistant pull request #118
Opened 2024-06-23 17:41 UTC by bassrock

# Goal
Add in support for window, door, motion, and occupancy sensors.

# Notes
Matter doesn't have direct support for all the types of binary sensors that exist on https://www.home-assistant.io/integrations/binary_sensor/ without being able to get more information like actual values of temperatures from the `sensor` entity that is likely attached to the parent device the entity is on. For all those types, I just mapped them to a generic [on/off sensor](https://github.com/project-chip/matter.js/blob/main/packages/matter.js/src/device/DeviceTypes.ts#L641)

I also used the examples at https://github.com/Luligu/matterbridge-eve-door/blob/main/src/platform.ts#L23 to figure out how to represent a "door" and "motion" sensor in matter.

2024-06-23 17:42 UTC, bassrock commented on src/devices/aspects/on-off-aspect.ts
> +    if (config?.turnOn) {
Conditionally adding these, so that they can be used as a sensor aspect

2024-06-23 22:09 UTC, t0bst4r requested changes

2024-06-23 22:09 UTC, t0bst4r commented on src/devices/binary_sensor-device.ts
> +    console.log(entity);
Please remove console.log

2024-06-23 22:09 UTC, t0bst4r commented on src/mocks/binary_sensor-mocks.ts
> +export const binarySesnorsMocks = {
1. Mocked devices are not used and will not work
2. I kept them for writing automated test in the future. So it’s nice to have them
3. Typo

2024-06-23 22:09 UTC, t0bst4r commented on src/devices/aspects/on-off-aspect.ts
> +    if (config?.turnOn) {
This will automatically break the existing entity types which use this aspect. If turn on or turn off is not explicitly configured, it is falling back to the generic `homeassistant.turn_on` service which will work for a lot of entity types automatically. 
If we make it optional to support sensors, we‘d need to explicitly configure it on each entity type.

2024-06-23 22:16 UTC, t0bst4r commented
Thank you a lot for your contribution!
Did you test if it’s working locally? You can run `yarn serve` to run it locally. 
if you want to build your own docker image, you could run 
1. `yarn build`
2. `yarn pack —filename docker/matterbridge-home-assistant.tgz`
3. `cd docker && docker build -t my-image .`

2024-06-28 13:54 UTC, bassrock commented
Yep i tested, locally will make the updates this weekend!

2024-06-30 15:24 UTC, bassrock commented
@t0bst4r Ok all updated, I realized that instead of on/off as a fallback, thats the same as a BooleanStateAspect without the control aspect 🤦 .

I was also looking at adding Sensors but I think there needs to be a way to grab the root device a homeassistant entity is attached to because sensor devices are usually tied to a few (ie air quality will have a few sensors to build out a full "device")

Happy to discuss this in a chat somewhere else too if interested

2024-06-30 16:24 UTC, t0bst4r approved these changes

2024-06-30 16:26 UTC, merged